### ISSUE TITLE
Gene KB subset

### ISSUE THREAD

**Issue by Chanwhistle** [sg-wbi/belb#1]
Hi, 
I need to find NCBIgene subset of nlm-gene and gnormplus .
How did you made subset of those KB?

![image](https://github.com/sg-wbi/belb/assets/81608527/62615161-2f21-4d1a-9fd9-ee99f497c02b)

**Comment by sg-wbi** [comment]
Hi,

thank you for your interest and sorry for the late reply.

If you have already built the KBs (`python -m belb.scripts.build_kbs --dir path/to/dir --cores 20`) then you should be able to load the kb with subset like this:

```python
from belb import AutoBelbKb
from belb.resources import Kbs

kb = AutoBelbKb.from_name(
                name=Kbs.NCBI_GENE.name,
                directory=path/to/dir,
                db_config=./db.yaml,
                subset="gnormplus",
            )
```

To get the actual NCBI Taxonomy identifiers of the species in the subset:

```python
from belb.resources import Kbs
from belb.utils import load_kb_subsets

subsets = load_kb_subsets(Kbs.NCBI_GENE.name)
print(subsets['gnormplus']
# [41856, 9986, 10116, 11908, 9606, 3847, 7955, 11676, 4896, 8355, 511145, 8364, 9913, 10298, 7227, 559292, 333760, 9031, 6239, 9823, 10090, 3702]
```

The subset data is stored in [this JSON file](https://github.com/sg-wbi/belb/blob/main/belb/metadata/ncbi_gene/subsets.json) in the repository
